name: example-environment
channels:
  - conda-forge
dependencies:
  - voila
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy
  - ipywidgets
